### Get list of all credentials
GET http://localhost:3900/api/v1/credentials

### Get single credential
GET http://localhost:3900/api/v1/credentials/1

### Create a new credential
POST  http://localhost:3900/api/v1/credentials
Content-Type: application/json

{
  "name": "OpenAI"
}

### Update a credential
PUT  http://localhost:3900/api/v1/credentials/1
Content-Type: application/json

{
  "name": "ClickUp"
}

### Delete a credential
DELETE  http://localhost:3900/api/v1/credentials/1